### PR TITLE
Shared: Block requests to nodes running beta, alpha and release IRI releases

### LINKED ISSUE #800: Send / Receive on used adresses
### Bug description
In 0.4.4: After a reset of trinity, and reimport of my previous used accounts, my transaction history was gone. So I did a manual sync and the adresses and balance showed up again. But the used adresses werent red and I was able to send to an used adress from one Trinity account to an another one! 
Even worse: I was then able to send from that used adress!

### Environment Specs
What device are you running Trinity on?

- Windows 7

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.4.
- Node: https://iota-2.de:14276

### Steps To Reproduce
1. Update to 0.4.4
2. Reset Wallet
3. Reimport previous used accounts

### Expected behaviour
Transaction history should be shown up with all used adresses. At least after a manual sync.

### Actual behaviour
No history. After manual sync all adresses are shown but without being marked as used.
So I could receive and send on used adresses.

https://thetangle.org/address/AAMCGFFOGRZVJLUBUBUQNTXUAUUWHNFJOBYVKNQLZMU9DWJBUHLMUJEOITGQSYSEJLGVHMJUFNQWJJGRD

### Errors
No errors. No error log.

### Am I planning to do it myself with a PR?
No.

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

Block requests to beta, alpha and release candidate nodes.

Fixes #800

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/shared/actions/alerts.js [hunk 1]
```diff
@@ -89,6 +89,17 @@ export const generateNodeOutOfSyncErrorAlert = () => (dispatch) => {
...
 
+/**
+ * Generates an error alert if a network call is made to an unsupported node
+ *
+ * @method generateUnsupportedNodeErrorAlert
+ *
+ * @returns {function} dispatch
+ */
+export const generateUnsupportedNodeErrorAlert = () => (dispatch) => {
+    dispatch(generateAlert('error', i18next.t('global:unsuppoortedNode'), i18next.t('global:unsuppoortedNodeExplanation')));
```
Comment (rajivshah3) [inline src/shared/actions/alerts.js]: This should be changed to match the names of the strings in the [translation.json](https://github.com/iotaledger/trinity-wallet/pull/805/files#diff-8448e7037db660ba08a9b7c6efaae24a)
```suggestion
    dispatch(generateAlert('error', i18next.t('global:experimentalNode'), i18next.t('global:experimentalNodeExplanation')));
```

**Review by rajivshah3 — CHANGES_REQUESTED** [review]

**Review by rajivshah3 — APPROVED** [review]

**Review by cvarley100 — APPROVED** [review]
