### PR TITLE
Persist account information during account setup

### LINKED ISSUE #585: Unhandled exceptions when a new account is added
### Bug description
There are some edge cases that aren't handled and they lead wallet to a state where it becomes completely unusable. 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone 6
- OS version: 12.1

- Trinity version:  0.5.1  (27)

### Steps To Reproduce
**Case 1** 
When _first_ account is added:
1. Add seed (Complete onboarding)
2. Close the app on loading screen
3. Reopen the app and try to login
4. Instead of calling [getFullAccountInfo](https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/ui/views/wallet/Loading.js#L171) it calls [getAccountInfo](https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/ui/views/wallet/Loading.js#L174). This will make wallet unusable because there is no account information added to `accounts` reducer. 

**Case 2** 
When _additional_ account is added: 
1. Add new seed
2. Close the app on loading screen
3. Reopen the app and login
4. Add new seed again. Trinity won't allow adding the seed this time because it already has a keychain entry. 

### Expected behaviour
**Case 1** 
It should successfully fetch account information and should not lead wallet to an unusable state.

**Case 2**
There should only be a keychain entry for a seed if account information is fetched and added to `accounts` reducer. 

### Actual behaviour

**Case 1** 
It blocks login.

**Case 2**
It blocks addition of a new seed.  

### Am I planning to do it myself with a PR?
Yes.

### PR DESCRIPTION
**Pull request by laumair**
# Description

Fixes https://github.com/iotaledger/trinity-wallet/issues/585

**Note:** This hasn't been tested with a ledger account.

## Type of change

- Bug fix

# How Has This Been Tested?

- Added unit test coverage

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/desktop/src/ui/views/onboarding/Login.js [hunk 1]
```diff
@@ -105,10 +111,18 @@ class Login extends React.Component {
      * @returns {undefined}
      */
     setupAccount = async () => {
-        const { wallet, currency, currentAccountName, currentAccountMeta } = this.props;
-
-        const accountName = wallet.addingAdditionalAccount ? wallet.additionalAccountName : currentAccountName;
-        const accountMeta = wallet.addingAdditionalAccount ? wallet.additionalAccountMeta : currentAccountMeta;
+        const {
+            wallet,
```
Comment (cvarley100) [inline src/desktop/src/ui/views/onboarding/Login.js]: This could be removed. It's only used for password. I suggest adding password to mapStateToProps

**Review by cvarley100 — CHANGES_REQUESTED** [review]

File: src/desktop/src/ui/views/onboarding/Login.js (hunk 1 above)
Comment (laumair) [reply src/desktop/src/ui/views/onboarding/Login.js]: Fixed with https://github.com/iotaledger/trinity-wallet/pull/587/commits/9977967a2c29a396365dec9d974a0315ae537df9

**Review by cvarley100 — APPROVED** [review]

**Review by rihardsgravis — APPROVED** [review]
