### PR TITLE
Mobile: General mobile bug fixing and refactoring

### LINKED ISSUE #519: Missing translations (crowdin translated to 100%)
### Bug description
Missing translations.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone
- OS version: IOS 12.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1

### Missing translations
- "Standard/Advanced" in settings menu Mode always shows Standard/Advanced instead of localized string, however the strings are shown correctly when using the switch to select between Standard and Advanced
- "Mode updated" and "You have changed to Standard/Advanced mode" are not localized, no strings on crowdin
- "Default/Classic/Mint/Electric/etc." theme names are not localized, although translated on crowdin
- "Sending {{ amount }} (= {{ fiat_amount }}) from {{ account_name }} to {{ address }}" is not localized, no string on crowdin (appears when one needs to confirm sending iota to an address)
- Status strings that are displayed above the progress bar during sending iota (like Preparing inputs, completing proof of work, etc.) are not localized
- "Attaching address (counter) / (max number)" is not localized, no string on crowdin (progress indicator during snapshot transition)

### LINKED ISSUE #706: Phone unresponsive 15-30 seconds after generating address
### Bug description
- Generating addresses a few times can lead to being unable to press the native android home button or exit the app. I am able to flip though menus but phone is unresponsive for 15-30 seconds before registering and acting upon all the buttons I tried to press before.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1 (28), Mobile

### Steps To Reproduce
1. go to receiving address tab,
2. generate new address
3. re-generate same address
4. find phone becomes unresponsive and user cannot leave the application. 
5. wait 30 seconds and phone will have pressed all the buttons you previously requested.

### Expected behavior
- There should be no 30 seconds of unresponsiveness from the device.

### Actual behavior
- Device is unresponsive to user requests for 30 seconds

### LINKED ISSUE #847: Text above circle while a tx gets promoted in Trinity Mobile
### Bug description
The text that indicated that the transaction gets promoted is above the circle. For example in the German language this string is long enough to reach the position of the circle.

Trinity mobile 0.6.0 (36) to (39)
iPhone 8 
iOS 11.3.1

### Expected behaviour
Circle should be behind the text.

### Actual behaviour
Longer text overlaps the circle.
img_3384

### LINKED ISSUE #911: empty password warning is sometimes too near to status bar
### Bug description
The empty password and unrecognized password warnings are sometimes nearer to the status bar as normal.

### Environment Specs
iPhone 8 iOS 11.3.1 and iPhone 5S iOS 12.0.1
Trinity mobile 0.6.0 (36) and (37)

### Steps To Reproduce
completely close Trinity App
next steps are visible in the video

### Expected behaviour
warnings should always have the same size and distance to the status bar

### Actual behaviour
after completely closing the app those warnings are nearer to the the status bar

video of this bug: https://www.youtube.com/watch?v=nx6SJkKdbQk

### LINKED ISSUE #975: [Google authenticator] typo when adding 2FA
### Bug description
When activating 2FA on Google authenticator, the code is named ":Trinity desktop wallet". I guess the colon is a misstype. 

### Environment Specs
- OS version: Linux Mint 19.1
- Trinity version: desktop 0.4.6
- Google Authenticator 5.00 for Android

### Steps To Reproduce
1. activate 2FA with Google authenticator

### Am I planning to do it myself with a PR?
No

### LINKED ISSUE #984: empty password warning is sometimes too near to status bar
reopened issue #911 

### Bug description
The empty password and unrecognized password warnings are sometimes nearer to the status bar as normal.

### Environment Specs
iPhone 8 iOS 11.3.1 and iPhone 5S iOS 12.0.1
Trinity mobile 0.6.0 (39)

### Steps To Reproduce
completely close Trinity App
next steps are visible in the video

### Expected behaviour
warnings should always have the same size and distance to the status bar

### Actual behaviour
after completely closing the app those warnings are nearer to the the status bar

video of this bug: https://youtu.be/OQ_pH1IJ3ro

### LINKED ISSUE #1128: Mobile: We have to manually click camera icon second time after granting Camera permissions
### Bug description
We have to manually click camera icon second time after granting Camera permissions when importing seed via qr code.

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

### Steps To Reproduce
1. Open fresh Trinity Mobile instance (initialize)
2. Click on I have seed already
3. Click on camera icon to scan QR code
4. Android asks for Camera permission
5. Grant it
6. qrcode scan screen only blinks for a second and then closes
7. You have to manually click camera icon again and then it works

### Expected behaviour
1. Open fresh Trinity Mobile instance (initialize)
2. Click on I have seed already
3. Click on camera icon to scan QR code
4. Android asks for Camera permission
5. Grant it
6. Scan screen works! Just works without any hiccups. ;)

### Am I planning to do it myself with a PR?
No

### LINKED ISSUE #1129: Mobile: Missing translations on Trinity "set up password" screen
### Bug description
PASSWORD and RETYPE PASSWORD not translated of first account creation screen

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

screenshot_20190222-182802_trinity

### LINKED ISSUE #1130: Mobile: "Bolt" icon on "Root Warning" screen is cut and low quality
### Bug description
When we have rooted device, that warning screen comes out on initial screen. The icon needs replacement to better quality and not to be cut.
Small thing but hurts my OCD. :D

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

screenshot_20190222-181924_trinity

### LINKED ISSUE #1133: Mobile: Language selector acts weird (GIF attached)
related: https://github.com/iotaledger/trinity-wallet/issues/677

### Bug description
- after setting up Trinity in PL language and after entering the settings, clicking the current language (Polish) we can see that English is selected anyway
- language selector acts weird as on the gif below (it only applies language when you select it straight from the list) but if you not choose anything and close the list it will apply ENG even if the PL is selected
- language sometimes resets itself to English

ezgif-1-54faba37881d

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

### Am I planning to do it myself with a PR?
No

### LINKED ISSUE #1137: Button event not fired when focus is on textbox
### Bug description
Example login:
If the password is entered and the keyboard is manually closed and the cursor with focus is still on the password textbox, the login button event is not triggered at the first time. The first click on the button is only focus lost on the textbox. Event is triggered at the second click.
Same for password change in settings menu, addresses in send menu, in general for all textbox-button combinations.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Huawei 
- Model: P20 Lite
- OS version: Android 8.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v 0.6.2 (49) latest

### Steps To Reproduce
1. Enter password in the textbox
2. Close the keyboard manually (cursor and focus still on the textbox)
3. Click on the login button
4. The focus is lost on the textbox but no button event is triggered

### Expected behaviour
Focus lost on textbox and button event is triggered with just one click.

### Actual behaviour
Focus lost on textbox but no button event is triggered. Only on the second click on the button.

### PR DESCRIPTION
**Pull request by cvarley100**
# Description

- Fixes loading screen coming from bottom on android (setStackRoot animation)
- Fixes Android status bar colour update delays
- Fixes empty password warning is too near to status bar on first app open
- Reduces quorum size
- Fixes incorrect topbar colour on print
- Refactor navigation
- Fixes clipboard clear alert trigger
- Fixes need to open QR modal twice in onboarding
- Fixes promotion animation overlap
- Fixes colon in Android 2FA QR Scan
- Fixes language selection dropdown behaviour
- Ensures manual address generation can only fire once at a time
- Ensure device does not sleep during migration
- Fixes unlocalised strings
- Fixes incorrect warning icon on root warning
- Enables button use while keyboard is active
- Fixes iPhone X mobile layout bug
- Fixes visual artefacts on T&C and Privacy transition on iPhone X
- Ensures correct colours are used on screen push
- Fixes iOS password fields focus positioning

Fixes #1133 
Fixes #975
Fixes #911
Fixes #847
Fixes #1128
Fixes #706
Fixes #1129
Fixes #519
Fixes #1130
Fixes #984 
Fixes #1137

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

- Tested across Android and iOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [x] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/mobile/src/ui/components/PasswordFields.js [hunk 1]
```diff
@@ -112,7 +107,7 @@ class PasswordFields extends Component {
         return (
             <View style={[styles.container]}>
                 <CustomTextInput
-                    label={passwordLabel}
+                    label={passwordLabel || i18next.t('global:password')}
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/PasswordFields.js]: We should use the `t` from the props instead (also need `const { t } = this.props;` on line 103):
```suggestion
                    label={passwordLabel || t('global:password')}
```

File: src/mobile/src/ui/components/PasswordFields.js [hunk 2]
```diff
@@ -140,7 +135,7 @@ class PasswordFields extends Component {
                     onRef={(c) => {
                         this.reentry = c;
                     }}
-                    label={reentryLabel}
+                    label={reentryLabel || i18next.t('setPassword:retypePassword')}
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/PasswordFields.js]:
```suggestion
                    label={reentryLabel || t('setPassword:retypePassword')}
```

File: src/mobile/src/ui/components/Slider.js [hunk 3]
```diff
@@ -183,12 +181,12 @@ class Slider extends Component {
     getText() {
         const { preSwipeText, postSwipeText, numberOfSliders } = this.props;
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/Slider.js]:
```suggestion
        const { preSwipeText, postSwipeText, numberOfSliders, t } = this.props;
```

File: src/mobile/src/ui/components/Slider.js [hunk 4]
```diff
@@ -183,12 +181,12 @@ class Slider extends Component {
...
         if (this.state.swipeComplete) {
-            return postSwipeText;
+            return postSwipeText || i18next.t('confirmed');
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/Slider.js]:
```suggestion
            return postSwipeText || t('confirmed');
```

File: src/mobile/src/ui/components/Slider.js [hunk 5]
```diff
@@ -183,12 +181,12 @@ class Slider extends Component {
...
         }
         if (numberOfSliders > 1) {
-            return preSwipeText + ' (' + this.state.sliderNumber + '/' + numberOfSliders + ')';
+            return (preSwipeText || i18next.t('swipeToConfirm')) + ' (' + this.state.sliderNumber + '/' + numberOfSliders + ')';
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/Slider.js]:
```suggestion
            return (preSwipeText || t('swipeToConfirm')) + ' (' + this.state.sliderNumber + '/' + numberOfSliders + ')';
```

File: src/mobile/src/ui/components/Slider.js [hunk 6]
```diff
@@ -183,12 +181,12 @@ class Slider extends Component {
...
         }
-        return preSwipeText;
+        return preSwipeText || i18next.t('swipeToConfirm');
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/Slider.js]:
```suggestion
        return preSwipeText || t('swipeToConfirm');
```

**Review by rajivshah3 — DISMISSED** [review]

File: src/mobile/src/libs/navigation.js [hunk 7]
```diff
@@ -14,7 +37,7 @@ export const navigator = {
                 Navigation.push('appStack', {
                     component: {
                         name: nextScreen,
-                        options,
+                        options: merge({}, options, getDefaultOptions(nextScreen)),
```
Comment (laumair) [inline src/mobile/src/libs/navigation.js]: Shouldn't `merge({}, options, getDefaultOptions(nextScreen))` be the other way around i.e., we want to merge `options` in `getDefaultOptions()` ?

File: src/mobile/src/ui/components/Migration.js [hunk 8]
```diff
@@ -130,7 +132,7 @@ class Migration extends Component {
         if (this.state.hasCompletedRealmMigration) {
             return t('seedMigrationExplanation');
         }
-        return t('dataMigrationExplanation') + ' ' + t('loading:thisMayTake');
+        return `${t('dataMigrationExplanation')} {t('loading:thisMayTake')} {t('doNotMinimise')}`;
```
Comment (laumair) [inline src/mobile/src/ui/components/Migration.js:135]: 👍

File: src/mobile/src/ui/components/SeedVaultImportComponent.js [hunk 9]
```diff
@@ -129,43 +131,50 @@ export class SeedVaultImportComponent extends Component {
...
+                    path = path.slice(7);
+                }
+                RNFetchBlob.fs
+                    .readFile(path, 'ascii')
+                    .then((data) => {
+                        this.setState({ seedVault: data });
+                        this.props.openPasswordValidationModal();
+                    })
+                    .catch(() =>
+                        generateAlert('error', t('seedVault:seedFileError'), t('seedVault:seedFileErrorExplanation')),
```
Comment (laumair) [inline src/mobile/src/ui/components/SeedVaultImportComponent.js]: We should use prop method `generateAlert` here otherwise it will refer to the imported `generateAlert` action.

File: src/mobile/src/ui/components/SeedVaultImportComponent.js [hunk 10]
```diff
@@ -129,43 +131,50 @@ export class SeedVaultImportComponent extends Component {
      * Opens document picker, reads chosen file and opens password validation modal
      * @method importSeedVault
```
Comment (laumair) [inline src/mobile/src/ui/components/SeedVaultImportComponent.js]: `importSeedVault` -> `showDocumentPicker`

File: src/mobile/src/ui/components/TopBar.js [hunk 11]
```diff
@@ -313,11 +317,17 @@ class TopBar extends Component {
...
+                    styles.titleWrapper,
+                    !isIPhoneX && { marginTop: Styling.statusBarHeight },
+                    { height: this.topBarHeight },
+                ]}
+            >
                 <TouchableWithoutFeedback
                     onPress={() => {
                         if (!shouldDisable) {
-                            if (accountNames.length > 1) {
+                            if (accountNames.length > 1 && !isKeyboardActive) {
```
Comment (laumair) [inline src/mobile/src/ui/components/TopBar.js:330]: Nice!

File: src/mobile/src/ui/theme/general.js [hunk 12]
```diff
@@ -54,3 +54,34 @@ export function getBackgroundColor(screen, theme, inactive = false) {
     };
     return screenMap[screen];
 }
+
+export function getBackgroundColor(screen, theme) {
+    const { bar, body } = theme;
+    const screenMap = {
```
Comment (laumair) [inline src/mobile/src/ui/theme/general.js]: Perhaps we should avoid this duplication by defining `screenMap` globally and then transforming it for wherever needed. It's also used in [getBorderColor](https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/ui/theme/general.js#L27).

File: src/mobile/src/ui/views/wallet/LanguageSelection.js [hunk 13]
```diff
@@ -77,10 +74,11 @@ class LanguageSelection extends Component {
...
     };
 
-    constructor() {
-        super();
-
-        this.languageSelected = currentLanguageLabel;
+    constructor(props) {
+        super(props);
+        this.state = {
+            languageSelected: props.language,
```
Comment (laumair) [inline src/mobile/src/ui/views/wallet/LanguageSelection.js:80]: Ideally, we should avoid props to state.

**Review by laumair — CHANGES_REQUESTED** [review]

File: src/mobile/src/ui/components/SeedVaultImportComponent.js (hunk 9 above)
Comment (cvarley100) [reply src/mobile/src/ui/components/SeedVaultImportComponent.js]: @laumair But we declare `generateAlert` in line 135

File: src/mobile/src/ui/views/wallet/LanguageSelection.js (hunk 13 above)
Comment (cvarley100) [reply src/mobile/src/ui/views/wallet/LanguageSelection.js:80]: We use props in state in many places. Why should it be avoided?

**Review by laumair — APPROVED** [review]
