### PR TITLE
Desktop: Prepare 0.6.2 release

### LINKED ISSUE #1538: Already spent from address after sending failed
### Bug description
I tried to make a transaction. Internet connection was bad and it failed at `Preparing inputs`. The log reported something like `could not get quorum subtangle milestone`. Directly after that I tried it a second time and this time it took more than a minute to `prepare inputs` and it failed at `Broadcasting` this time. The error log shows the same error again that occurred on the first try. Now this tx is shown in the history and Trinity tries to reattach but always fails with `Already spent from address`. 
After some time my tx got confirmed but after restarting Trinity it's still shown as not confirmed. After refreshing history it's shown as confirmed again but Trinity still tries and fails to reattach.

Seems to be related to: #1036 and maybe #1386

### Environment Specs
What device are you running Trinity on?

- Model: iPhone 8
- OS version: 12.1.1
- Trinity version: 0.7.0(61)

### Steps To Reproduce
1. make a transaction
2. after it failed try again
3. reattach it in history after it failed a second time

### Expected behaviour
Trinity should reattach the failed tx normally.

### Actual behaviour
It always reports `Already spent from address` when trying to reattach the failed transaction.

### Errors
IMG_4587
IMG_E4588
IMG_E4590

### PR DESCRIPTION
**Pull request by cvarley100**
Fix: Migration not successful when migrating from 0.4.x and below to latest (#1832)
Fix: Incorrect already spent from address errors on transaction retry (#1835)
Fix: Incorrect transaction failure alert when successfully broadcast (#1835)
Fix: Quorum being conducted on transaction account syncs when explicitly turned off (#1835)
Fix: Error-related crashes (#1833)
Update: Add remote node list endpoint back-ups (#1811)
Update: Add more verbose error log messages (#1834)
Update: New translations (#1826)

Closes #1538, #1386, #1815, #1422

### CODE REVIEW

File: src/desktop/src/ui/global/About.js [hunk 1]
```diff
@@ -59,6 +59,17 @@ export class AboutComponent extends React.PureComponent {
 
                     <article>
                         <Scrollbar>
+                            <h5>0.6.2</h5>
+                            <ul>
+                                <li>Fix: Migration not successful when migrating from 0.4x and below to latest</li>
```
Comment (rihardsgravis) [inline src/desktop/src/ui/global/About.js]:
```suggestion
                                <li>Fix: Migration not successful when migrating from 0.4.x and below to latest</li>
```

**Review by rihardsgravis — APPROVED** [review]
