### PR TITLE
fix/mobile: autocapitalise seed entry

### LINKED ISSUE #2501: Seed should be autocapitalised
### Bug description
Users must turn on caps lock to manually enter a seed. It ought to be autocapitalised to avoid this friction point.

### Environment Specs

iOS/Android 1.2.0

### PR DESCRIPTION
**Pull request by cvarley100**
# Description

Autocapitalises seed on entry.

Fixes #2501 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested on Android and iOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes

### CODE REVIEW

**Review by laumair — APPROVED** [review]
Looks good to me!

File: src/mobile/src/ui/components/CustomTextInput.js [hunk 1]
```diff
@@ -226,10 +226,11 @@ class CustomTextInput extends Component {
     onChangeText(value) {
         const { isPasswordInput, isSeedInput, onValidTextChange } = this.props;
         if (isSeedInput) {
-            if (value && !value.match(VALID_SEED_REGEX)) {
+            const valueCapitalized = value.toUpperCase()
+            if (valueCapitalized && !valueCapitalized.match(VALID_SEED_REGEX)) {
```
Comment (holiman) [inline src/mobile/src/ui/components/CustomTextInput.js:230]: Both before this change and after -- so if `valueCapitalized` is `""`, the regex-check won't trigger, and the empty seed will go to `onValidTextChange` -- ?

Comment (holiman) [reply src/mobile/src/ui/components/CustomTextInput.js:230]: Should probably be
```javascript
if (!valueCapitalized || !valueCapitalized.match(VALID_SEED_REGEX)) {
    return;
}
```
