### PR TITLE
Fix frozen splash screen issue on android

### LINKED ISSUE #851: Trinity Mobile freeze after fresh install (or after deleting app data)
### Bug description
Trinity hangs/freezes on splash screen after first open of the Trinity app (fresh install)
_I would consider this one as an important thing to fix._

### Environment Specs
Tested and reproduced on:
- Samsung Galaxy S8  (Android 8.0)
- Samsung Galaxy S9+ (Android 8.0)
- Honor Play (Android 8.1.0)

### Trinity version: 
Reproduced both on **0.5.1** and **0.6.0 (alpha)**

### Steps To Reproduce
1. Uninstall and Install Trinity Mobile (or delete data app of existing install)
2. Open Trinity (the Trinity logo will show up and app will hang on this screen forever)

**(after full app close and restart, everything is working again as supposed to)**

### Expected behaviour
Fresh install of Trinity Mobileshould work perfectly from the first try!

### Actual behaviour
Trinity hangs/freezes on splash screen after first open of the Trinity app (fresh install).

### PR DESCRIPTION
**Pull request by laumair**
# Description

Will fix https://github.com/iotaledger/trinity-wallet/issues/851

## Type of change

- Bug fix

# How Has This Been Tested?

- Manually tested on android (debug)

# Checklist:
- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

**Review by rajivshah3 — APPROVED** [review]

File: src/mobile/src/libs/store.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ export const migrate = (store, restoredState) => {
         const propsToReset = [];
 
         // FIXME: Temporarily needed for node list reset
-        if (restoredState.settings.versions.buildNumber < 32) {
+        if (get(restoredState, 'settings.versions.buildNumber') < 32) {
```
Comment (rajivshah3) [inline src/mobile/src/libs/store.js:90]: Just out of curiosity, what's the difference between directly accessing the property vs. using `get`?

Comment (laumair) [reply src/mobile/src/libs/store.js:90]: [lodash.get](https://lodash.com/docs/4.17.11#get) won't throw on `undefined` properties. `{}.settings.versions.buildNumber` will.

Comment (rajivshah3) [reply src/mobile/src/libs/store.js:90]: Ah, I see
