### PR TITLE
Mobile: Reset wallet if credentials are missing

### LINKED ISSUE #412: TypeError in src/libs/keychain.js:69
## Error in Trinity Mobile

**TypeError** in **src/libs/keychain.js:69**
null is not an object (evaluating 'e.item')

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ba36c3fffe75a00193f3071?event_id=5ba658ea002f780017690003&i=gh&m=ci)

## Stacktrace

    src/libs/keychain.js:69 - 

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ba36c3fffe75a00193f3071?event_id=5ba658ea002f780017690003&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

### PR DESCRIPTION
**Pull request by rajivshah3**
# Description
Resets the wallet if the redux state says the onboarding was completed, but credentials are missing from the keychain. This normally occurs if the device was restored from an existing iCloud backup.

Fixes #412 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?
Manually tested on iOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes

### CODE REVIEW

File: src/mobile/src/libs/keychain.js [hunk 1]
```diff
@@ -64,6 +64,15 @@ export const getPasswordHash = async (password) => {
     return await generatePasswordHash(password, salt);
 };
 
+export const doesSaltExistInKeychain = async () => {
```
Comment (laumair) [inline src/mobile/src/libs/keychain.js]: `async` keyword can be removed from here.

File: src/mobile/src/ui/routes/entry.js [hunk 2]
```diff
@@ -79,6 +86,26 @@ const renderInitialScreen = (initialScreen) => {
...
+                .then(() => {
+                    state.dispatch(resetWallet());
+                    // Set the new app version
+                    state.dispatch(
+                        setAppVersions({
+                            version: getVersion(),
+                            buildNumber: getBuildNumber(),
+                        }),
+                    );
+                    return initApp(state);
```
Comment (laumair) [inline src/mobile/src/ui/routes/entry.js]: This might initialise the app instance twice. 

See https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/libs/store.js#L5 

The app initialisation is triggered as a callback _after_ the persisted state is restored https://github.com/iotaledger/trinity-wallet/blob/develop/src/mobile/src/libs/store.js#L60

Comment (laumair) [reply src/mobile/src/ui/routes/entry.js]: I would suggest resetting keychain with the state migration setup.

**Review by laumair — DISMISSED** [review]

**Review by cvarley100 — APPROVED** [review]
