### PR TITLE
Desktop: Ledger functionallity and UX bugfixes

### LINKED ISSUE #1088: unable to cancel refreshing history without Ledger connected
### Bug description
When trying to refresh the history of a ledger account without the Ledger connected Trinity shows the `Connect your Ledger` message. But clicking the `Cancel ` button doesn't really cancel the refresh. Trinity tries to refresh the history again and asks again to connect the Ledger. So it is like an endless loop and it is impossible to really cancel this process without connecting the Ledger Nano S. Just restarting Trinity cancels it.
It is the same with the `Open Ledger IOTA app` message.

### Environment Specs
- OS version: Windows 10

- Trinity version: 0.5.0 alpha

### Steps To Reproduce
1. click on refresh button on a ledger account
2. click cancel button at the `Connect your Ledger` message

### Expected behaviour
Refreshing should be canceled. Using other accounts again should be possible.

### Actual behaviour
Trinity always tires to refresh the account again although `Cancel` was clicked.

### Am I planning to do it myself with a PR?
No

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

- Fix receive closes automatically on Ledger account
- Fix unable to cancel refreshing history without Ledger connected
- Fix onboarding seed not available after failed initial account fetch

Fixes #1088, #1085

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on macOS, Windows 10, Ubuntu linux

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/desktop/native/hardware/Ledger.js [hunk 1]
```diff
@@ -66,7 +65,7 @@ class Ledger {
                 if (message && message.abort) {
                     this.removeListener(callbackSuccess);
                     ipc.removeListener('ledger', callbackAbort);
-                    reject(connectionError);
+                    reject(Errors.LEDGER_CANCELLED);
```
Comment (laumair) [inline src/desktop/native/hardware/Ledger.js:68]: Shouldn't this be rejected with an `Error` object because [here](https://github.com/iotaledger/trinity-wallet/pull/1101/files#diff-ac38395aefdae2edd45175f6f364bb25R465 ) you are checking on `message` ?

**Review by laumair — APPROVED** [review]

**Review by rajivshah3 — APPROVED** [review]

**Comment by rajivshah3** [comment]
Can we merge this to `develop` so that the new strings are sent to Crowdin?

File: src/desktop/native/hardware/Ledger.js (hunk 1 above)
Comment (rihardsgravis) [reply src/desktop/native/hardware/Ledger.js:68]: This error is catched at https://github.com/iotaledger/trinity-wallet/blob/6013bc45a0e223c8eb01d2b01a4ceed3ec1961f4/src/shared/libs/iota/utils.js#L336 which returns an `Error` object
