### PR TITLE
Temporarily disable SeedVault on iPhone XS/XS Max/XR

### LINKED ISSUE #416: Crash on EnterSeed screen on iPhone XS/XR
## Error in Trinity Mobile

**N2Js19JavascriptExceptionE** in **unknown method**

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ba4c32ee1ce1200194f94f1?event_id=5ba7c06d002f5cd96bab0000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ba4c32ee1ce1200194f94f1?event_id=5ba7c06d002f5cd96bab0000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  20

Application Specific Information:
abort() called
```

### PR DESCRIPTION
**Pull request by rajivshah3**
# Description
Temporarily disables SeedVault on iPhone XS/XS Max/XR. 

Fixes #416 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] `nodejs-mobile` does not start on iPhone XS when navigating to SeedVault-related screens
- [x] Normal functionality is preserved on other devices

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas [ ] 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/mobile/src/libs/device.js [hunk 1]
```diff
@@ -3,13 +3,22 @@ import DeviceInfo from 'react-native-device-info';
...
 
 export const locale = DeviceInfo.getDeviceLocale();
 
 export const isAndroid = Platform.OS === 'android';
 export const isIOS = Platform.OS === 'ios';
 export const isIPhoneX = device.includes('iPhone X');
 
+export const isIPhone11 = () => {
+    // Check if device is iPhone XS, iPhone XS Max, or iPhone XR
+    if (deviceId.substring(0, 8) === 'iPhone11') {
```
Comment (laumair) [inline src/mobile/src/libs/device.js]: Could be simplified to just `return deviceId.substring(0, 8) === 'iPhone11'`.

Comment (laumair) [reply src/mobile/src/libs/device.js]: Also we could just do `export const isIPhone11 = deviceId.substring(0, 8) === 'iPhone11`

File: src/mobile/src/ui/views/onboarding/EnterSeed.js [hunk 2]
```diff
@@ -85,6 +85,7 @@ class EnterSeed extends React.Component {
         this.state = {
             seed: '',
             isModalVisible: false,
+            isIPhone11: isIPhone11(),
```
Comment (laumair) [inline src/mobile/src/ui/views/onboarding/EnterSeed.js]: I don't think this should be set to state. We should be able to just use it directly.

**Review by laumair — CHANGES_REQUESTED** [review]

**Review by cvarley100 — APPROVED** [review]
