### PR TITLE
Deskop 0.5.2 release

### LINKED ISSUE #1630: Seeing install libsecret-1-dev message even if its installed
### Bug description
With this version trinity-desktop-0.5.1.AppImage  i am seeing libsecret error.
It is asking me to install libsecret-1-dev. I installed it but still seeing this issue.
Someone in discord asked me to check if gnome-keyring is installed. gnome-keyring was installed in my system before i install libsecret-1-dev

### Environment Specs
I am running it on ubuntu 18.04

What build of Trinity are you running? 
trinity-desktop-0.5.1.AppImage

### Steps To Reproduce
Just start that app from terminal.

### Expected behaviour
App should have started, i should have seen authentication screen.

### Actual behaviour
What really happened.

### Errors
Screen Shot 2019-05-27 at 5 17 39 PM

Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

- Fix: Chart and price API calls (#1595)
- Fix: Skip retry failed transactions when password is not available (#1602)
- Fix: Ledger onboarding loads forever without reporting an error (#1603)
- Fix: Linux wallet incorrect reports "Missing security dependencies" (#1638)
- Update: Add Snapshot Transition reminder warning for new accounts that use existing seeds (#1643)

Fixes #1630

## Type of change

- New release

# How Has This Been Tested?

Tested on:

- [x] Ubuntu 18.04
- [x] Linux Mint 18.3
- [x] Windows 10
- [x] macOS 10.14

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: src/desktop/src/ui/global/About.js [hunk 1]
```diff
@@ -59,14 +59,25 @@ export class AboutComponent extends React.PureComponent {
 
                     <article>
                         <Scrollbar>
+                            <h5>0.5.2</h5>
+                            <ul>
+                                <li>Fix: Chart and price API calls</li>
+                                <li>Fix: Skip retry failed transactions when password is not available </li>
+                                <li>Fix: Ledger onboarding loads forever without reporting an error</li>
+                                <li>Fix: Linux wallet incorrectl reports &quot;Missing security dependencies&quot;</li>
```
Comment (rajivshah3) [inline src/desktop/src/ui/global/About.js]:
```suggestion
                                <li>Fix: Linux wallet incorrectly reports &quot;Missing security dependencies&quot;</li>
```

File: src/desktop/src/ui/global/About.js [hunk 2]
```diff
@@ -59,14 +59,25 @@ export class AboutComponent extends React.PureComponent {
...
+                                <li>
+                                    Update: Add Snapshot Transition reminder warning for new accounts that use existing
+                                    seed
```
Comment (rajivshah3) [inline src/desktop/src/ui/global/About.js]:
```suggestion
                                    seeds
```

**Review by cvarley100 — APPROVED** [review]
