### PR TITLE
Use local time for SeedVault export file

### LINKED ISSUE #679: SeedVault timestamp in filename uses UTC instead of local time
### Bug description
Exported SeedVault filenames are mismatched by 1hour both for Desktop and Mobile.

**Android:**
screenshot_20181130-215737_my files

**PC:**
time-mismatch-seedvault export

### Environment Specs
Desktop: Windows 7 x64
Samsung Galaxy S9+: Android 8.0

- Trinity version:
0.4.3 desktop
0.5.1 (28) mobile

### Expected behaviour
Time should match in SeedVault filenames.

### Am I planning to do it myself with a PR?
No

### PR DESCRIPTION
**Pull request by laumair**
# Description

Fixes https://github.com/iotaledger/trinity-wallet/issues/679

## Type of change

- Enhancement 

# How Has This Been Tested?

- Manually tested iOS (debug)

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/mobile/src/ui/components/SeedVaultExportComponent.js [hunk 1]
```diff
@@ -94,6 +94,30 @@ class SeedVaultExportComponent extends Component {
...
+
+        return `${isAndroid ? RNFetchBlob.fs.dirs.DownloadDir : RNFetchBlob.fs.dirs.CacheDir}/${prefix}${
+            // Use local time
+            new Date(
+                now.getTime() - now.getTimezoneOffset() * 60000, // convert minutes to ms because getTime unit is ms
+            )
+                .toISOString()
+                .slice(0, 16)
+                .replace(/[-:]/g, '')
+                .replace('T', '-')
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/SeedVaultExportComponent.js]: I think this will be cleaner if we import `moment` from `shared` and simply do `moment().format('YYYYMMDD-HHmm');` to achieve the [same result](https://jsfiddle.net/c6otpr28/1/). If you want I can do a PR for that to your branch

Comment (laumair) [reply src/mobile/src/ui/components/SeedVaultExportComponent.js]: Thanks @rajivshah3. I like your suggestion. Done in https://github.com/iotaledger/trinity-wallet/pull/1178/commits/eccf2f496cfb5ff7d238f469276706bc09b5be99

**Review by rajivshah3 — APPROVED** [review]
Looks good!

File: src/mobile/src/ui/components/SeedVaultExportComponent.js [hunk 2]
```diff
@@ -94,6 +95,21 @@ class SeedVaultExportComponent extends Component {
...
+     * @method getPath
+     *
+     * @param {string} prefix
+     *
+     * @returns {string}
+     */
+    static getPath(prefix) {
+        return `${
+            isAndroid ? RNFetchBlob.fs.dirs.DownloadDir : RNFetchBlob.fs.dirs.CacheDir
+        }/${prefix}${moment().format('YYYYMMDD-HHmm')}.kdbx`;
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/SeedVaultExportComponent.js]: Should this have a dash after the prefix?
```suggestion
        }/${prefix}-${moment().format('YYYYMMDD-HHmm')}.kdbx`;
```

Comment (laumair) [reply src/mobile/src/ui/components/SeedVaultExportComponent.js]: To match the path in desktop implementation, yes.
