### PR TITLE
Desktop: Add missing and fix usage of existing locales

### LINKED ISSUE #308: Missing translations in Trinity desktop (crowdin translated to 100%)
### Bug description
Missing translations (almost all of them are already translated on crowdin for PL lang but not added to Trinity)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: PC
- OS version: Windows 7 x64

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.3

### Missing translation lines:
- "All" (on transaction type selector)
- "BETA version warning: Do not send large amounts with this wallet."
- "Close" (also on TRINITY INFO screen)
- "Drop SeedVault file here or click to browse"
- "Help" -> "Trinity Help" (on menu -> help)
- "Randomise x characters to continue" (BLUE BUTTON on seed generator screen)
- "THEME" and "LABEL" (theme selector)
- "You must save your seed with" ... "of the options listed below." (only center part is translated -> see screenshots)
- Theme names (at least DEFAULT, CLASSIC should be translated (or all))

### Screenshots
all
beta version close
drop seedvault
help trinity help
randomise characters
theme label
themenames
you must save of the options

### LINKED ISSUE #309: Missing colon in transaction details
### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Desktop
- OS version: Windows 7 x64

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.3

### Errors
Missing colon "**:**" after "**Message**" on transaction details.
Small thing but it would be great to have everything perfect.

### Screenshot
no colon on message

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

Add missing locales and update incorrect usage of existing ones, see https://github.com/iotaledger/trinity-wallet/issues/308#issuecomment-417473029 

Fixes #308 
Fixes #309 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on macOS by switching the default locale

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

File: src/desktop/src/ui/components/Dropzone.js [hunk 1]
```diff
@@ -134,7 +134,8 @@ class Dropzone extends React.Component {
                 <h5 onClick={this.open}>
                     <Icon icon="seedVault" size={48} />{' '}
                     <span>
-                        {t('seedVault:')} Drop SeedVault file here<br /> or click to browse
+                        {t('seedVault:dropSeedVaultHere')} <br/>
+                        {t('seedVault:orClickToBrowse')}
```
Comment (rajivshah3) [inline src/desktop/src/ui/components/Dropzone.js]: Instead of breaking the strings apart, it's best if we simply add the `<br />` to the translation string and let the translators put it in

File: src/desktop/src/ui/views/onboarding/SeedGenerate.js [hunk 2]
```diff
@@ -165,9 +165,7 @@ class GenerateSeed extends React.PureComponent {
                             ) : null
                         }
                     >
-                        <p>
-                            Press <strong /> individual letters to randomise them.
-                        </p>
+                        <p>{t('newSeedSetup:individualLetterCount', { letterCount: clicksLeft })}</p>
```
Comment (rajivshah3) [inline src/desktop/src/ui/views/onboarding/SeedGenerate.js]: This should use i18next's plural feature. I can do a PR for this to your branch

**Review by rajivshah3 — APPROVED** [review]
