### PR TITLE
Specify maxLength for message textboxes

### LINKED ISSUE #1879: App will crash if message is too long when creating a QR code
## Error in Trinity Desktop

**Error** in **/wallet/receive**
code length overflow. (23668>23648)

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5d13e5004454840019921aa4?event_id=5d13e7b80045fd3649fd0000&i=gh&m=ci)

## Stacktrace

    iota://dist/bundle.js:32639 - Function.QRCode.createData

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5d13e5004454840019921aa4?event_id=5d13e7b80045fd3649fd0000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

### PR DESCRIPTION
**Pull request by Thoralf-M**
Fixes #1879

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

### CODE REVIEW

File: src/mobile/src/ui/components/MultiTextInput.js [hunk 1]
```diff
@@ -9,6 +9,8 @@ import { width, height } from 'libs/dimensions';
 import { Styling } from 'ui/theme/general';
 import { getThemeFromState } from 'shared-modules/selectors/global';
 import AmountTextInput from './AmountTextInput';
+import { /*MAX_TAG_LENGTH,*/ MAX_MESSAGE_LENGTH } from 'shared-modules/libs/iota/utils';
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/MultiTextInput.js:11]: ESLint is showing an error here:

```

/workdir/src/mobile/src/ui/components/MultiTextInput.js
--
  | 12:56  error  Absolute imports should come before relative imports  import/first

```
This can be solved by moving this line above line 11

**Review by rajivshah3 — CHANGES_REQUESTED** [review]

File: src/desktop/src/ui/components/input/Text.js [hunk 2]
```diff
@@ -47,6 +48,7 @@ export default class Text extends React.PureComponent {
                         type="text"
                         value={value}
                         onChange={(e) => onChange(e.target.value)}
+                        maxLength={MAX_MESSAGE_LENGTH}
```
Comment (rajivshah3) [inline src/desktop/src/ui/components/input/Text.js]: This will limit all text fields to 1093 characters. Instead, we should pass a `maxLength` prop which will be used similar to the `label` prop

Comment (Thoralf-M) [reply src/desktop/src/ui/components/input/Text.js]: I'm not sure how that should look, should it be like
```
...   
/** Limit max text length */
maxLength: PropTypes.integer,
...
const { value, label, maxLength, onChange, disabled } = this.props;
```
?

Comment (rajivshah3) [reply src/desktop/src/ui/components/input/Text.js]: Yep, that's correct. You'll still need this part though:

```
<input
    maxLength // this is short for maxLength={maxLength}
/>
```

File: src/desktop/src/ui/components/input/Text.js [hunk 3]
```diff
@@ -20,6 +20,8 @@ export default class Text extends React.PureComponent {
          * @param {string} value - Current input value
          */
         onChange: PropTypes.func.isRequired,
+        /** Limit max text length */
+        maxLength: PropTypes.integer,
```
Comment (rajivshah3) [inline src/desktop/src/ui/components/input/Text.js]: Whoops, this is actually called `number` 😬 

```suggestion
        maxLength: PropTypes.number,
```

**Review by rajivshah3 — APPROVED** [review]
Looks good, thanks @Thoralf-M !

Tested on iOS and macOS
