### PR TITLE
Desktop: Check for a unique seed for keychain type accounts

### LINKED ISSUE #681: Desktop - We can add the same seed many times
### Bug description
The same seed can be added many times on Trinity Desktop

### Environment Specs
PC - Windows 7

- Trinity version: 
0.4.3 

### Steps To Reproduce
1. Create account with your certain seed
2. Create another account with the same seed
3. Create another account with the same seed
4. Repeat forever because Trinity Desktop allows you :D **(on Trinity Mobile, this isn't allowed and we're receiving an allert)**

### Expected behaviour
We should receive an alert like in Trinity Mobile when we're trying to add the same seed again.

### Am I planning to do it myself with a PR?
No

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

Add unique seed check for keychain type accounts

Fixes #681

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/desktop/src/libs/SeedStore/Keychain.js [hunk 1]
```diff
@@ -195,6 +195,40 @@ class Keychain {
...
+        try {
+            const accounts = vault.filter((acc) => acc.account !== ACC_MAIN && acc.account !== `${ACC_MAIN}-salt`);
+
+            for (let i = 0; i < accounts.length; i++) {
+                const account = accounts[i];
+
+                const vaultSeed = await decrypt(account.password, this.key);
+
+                if (
+                    vaultSeed.length === seed.length &&
```
Comment (rajivshah3) [inline src/desktop/src/libs/SeedStore/Keychain.js:217]: Doesn't this check make this one redundant? https://github.com/iotaledger/trinity-wallet/blob/f050c68d1d44ab1ec3adaa50f8b2310ce197124b/src/desktop/src/ui/views/onboarding/SeedVerify.js#L86

Comment (rihardsgravis) [reply src/desktop/src/libs/SeedStore/Keychain.js:217]: The seeds checked against could not be the same length as the input seed (in theory it should, but you never know).

**Review by rajivshah3 — APPROVED** [review]
