### PR TITLE
Shared: Adds exchange support

### LINKED ISSUE #2401: Cannot accept terms of moonpay (german UI)
### Bug description
Cannot accept terms of moonpay (german UI). The bug is indicated by the orange lines.
In english UI it works as the text fits there.

20191219_043925000_iOS

### Environment Specs
- Manufacturer: Apple
- Model: iPhone SE
- OS version: iOS 13.3
- Trinity version: v 1.2.0 (95)

### Steps To Reproduce
just perform the necessary steps to reach the step seen on the screenshot.

### Expected behaviour
A linebreak would be good.

### Actual behaviour
The checkbox to accept the terms is not visible.

### PR DESCRIPTION
**Pull request by laumair**
# Description

- Adds MoonPay support across Mobile and Desktop

Fixes #2401

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

- Tested extensively across mobile and desktop

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [x] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

### CODE REVIEW

**Review by cvarley100 — APPROVED** [review]

File: src/mobile/ios/EntangledIOS/EntangledIOS.m [hunk 1]
```diff
@@ -31,7 +31,7 @@ @implementation EntangledIOS
 }
 
 // Bundle Proof of Work
-RCT_EXPORT_METHOD(bundlePow:(NSArray *)trytes trunk:(NSString*)trunk branch:(NSString*)branch minWeightMagnitude:(NSNumber * _Nonnull)minWeightMagnitude resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
+RCT_EXPORT_METHOD(bundlePow:(NSArray *)trytes trunk:(NSString*)trunk branch:(NSString*)branch minWeightMagnitude:(int)minWeightMagnitude resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
```
Comment (rajivshah3) [inline src/mobile/ios/EntangledIOS/EntangledIOS.m]: Was `NSNumber` causing problems?

File: src/mobile/ios/EntangledIOS/EntangledKit.framework/Headers/Interface.h [hunk 2]
```diff
@@ -15,13 +15,13 @@
 @interface EntangledIOSBindings : NSObject
 
 + (NSString*)iota_ios_digest:(NSString*)trytes;
-+ (NSString*)iota_ios_pow_trytes:(NSString*)trytes mwm:(NSNumber*)mwm;
++ (NSString*)iota_ios_pow_trytes:(NSString*)trytes mwm:(int)mwm;
```
Comment (rajivshah3) [inline src/mobile/ios/EntangledIOS/EntangledKit.framework/Headers/Interface.h:18]: The current `Interface.h` uses `NSNumber` instead of `int`:
https://github.com/iotaledger/entangled/blob/dfc34e2b61af415c451b32078f592069a14f4590/mobile/ios/Interface.h#L18

Was this built from a different branch?

**Review by rihardsgravis — APPROVED** [review]
Desktop side looks good to me!

**Comment by rigwild** [comment]
Oups! afed8ba7d4af832afba80d653f9b7ca687822777

https://github.com/iotaledger/trinity-wallet/blob/2bc40450f832124de189a866409d1e7cdb20721b/src/desktop/src/index.js#L40-L44
