### PR TITLE
Desktop: Settings view UI layout fixes

### LINKED ISSUE #846: "Remove custom node" button is smaller than "Save"
### Bug description
"Remove custom node" button is smaller than "Save" button in Node settings when a custom node is selected

### Environment Specs
Trinity 0.4.6 
Windows 10

### Expected behaviour
Those buttons should have the same size.
trinity0

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

- Fix Settings narrow layout to show only active submenu Icons
- Fix Account settings -> Addresses list layout
- Fix Node settings "Remove custom node" button style

Fixes #846 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Tested manually on macOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: src/desktop/src/ui/views/settings/account/Addresses.js [hunk 1]
```diff
@@ -24,39 +25,37 @@ class Addresses extends PureComponent {
...
-                                            </p>
-                                            <strong>
-                                                {formatValue(account.addresses[item].balance)}
-                                                {formatUnit(account.addresses[item].balance)}
-                                            </strong>
-                                        </li>
-                                    );
-                                })}
-                        </Scrollbar>
+                        {Object.keys(account.addresses)
```
Comment (rajivshah3) [inline src/desktop/src/ui/views/settings/account/Addresses.js]: Could the use of `Object.keys` cause problems with the order that addresses are shown in? We've had similar issues in the past that stemmed from the fact that `Object.keys` does not guarantee order

Comment (rihardsgravis) [reply src/desktop/src/ui/views/settings/account/Addresses.js]: Updated to sort the addresses by index in descending order.

**Review by rajivshah3 — APPROVED** [review]
