### PR TITLE
Desktop: FatalError component Linux fix

### LINKED ISSUE #1630: Seeing install libsecret-1-dev message even if its installed
### Bug description
With this version trinity-desktop-0.5.1.AppImage  i am seeing libsecret error.
It is asking me to install libsecret-1-dev. I installed it but still seeing this issue.
Someone in discord asked me to check if gnome-keyring is installed. gnome-keyring was installed in my system before i install libsecret-1-dev

### Environment Specs
I am running it on ubuntu 18.04

What build of Trinity are you running? 
trinity-desktop-0.5.1.AppImage

### Steps To Reproduce
Just start that app from terminal.

### Expected behaviour
App should have started, i should have seen authentication screen.

### Actual behaviour
What really happened.

### Errors
Screen Shot 2019-05-27 at 5 17 39 PM

Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

### PR DESCRIPTION
**Pull request by rihardsgravis**
# Description

Desktop's `FatalError` component would yield `Missing security dependencies` error on Linux also for application initialisation (e.g. Realm) errors.

Fixes #1630 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested on macOS, Ubuntu Linux

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/desktop/src/ui/global/FatalError.js [hunk 1]
```diff
@@ -33,39 +32,46 @@ const FatalError = ({ error }) => {
...
-                </ul>
-            </form>
-        );
-    };
+        if (
+            typeof error === 'string' &&
+            [
+                'The name org.freedesktop.secrets was not provided by any .service files',
+                'Cannot create an item in a locked collection',
+                'Unknown or unsupported transport \'disabled\' for address \'disabled:\'',
```
Comment (rajivshah3) [inline src/desktop/src/ui/global/FatalError.js]: Is it possible to match an error code instead of the localized message? This error may appear as `Unbekannter oder nicht unterstützter Transport »disabled« für Adresse »disabled:«` if the system language is German, for example ([see Bugsnag event](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5ce6a1f1dfbdf60019b3a725?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Brelease.seen_in%5D%5B%5D%5Btype%5D=eq&filters%5Brelease.seen_in%5D%5B%5D%5Bvalue%5D=latest&event_id=5ce71497003d62b26bf70000)). If `en-GB` is used, the message might use double quotes instead of single: `Unknown or unsupported transport “disabled” for address “disabled:”`.

Comment (rihardsgravis) [reply src/desktop/src/ui/global/FatalError.js]: There's no error code available (only a string type error) :/ What we could do is regex match that error to `/disabled(.*)disabled:/g`.

Comment (rajivshah3) [reply src/desktop/src/ui/global/FatalError.js]: Yeah, that would be best I think

**Review by cvarley100 — APPROVED** [review]
