### PR TITLE
[#662] Increasing space between columns

### LINKED ISSUE #662: Mobile: Choose node overlaps with node address
### Bug description
Choose node title overlaps with node address which looks bad.
screenshot_20181129-050942_trinity

### Environment Specs
Samsung Galaxy S9+
Android 8.0

- Trinity version: 
0.5.1 (28)

### Expected behaviour
Maybe make address of the node shorter like https://pow5.iota.comm... or remove "https://" from all node names on this screen so we would have only "main" address "pow5.iota.community:443" or even without port
screenshot_20181129-050942_trinitye

### Am I planning to do it myself with a PR?
No

### PR DESCRIPTION
**Pull request by delki8**
# Description
Increasing the space between all two-columns line managed by SettingsContent.js
Fixes #662 

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?
- Open the app with selected language as English
- Change it to Portuguese (Brazil) or other in witch 'Selected server' can be translated to something larger.
- Now instead of touching each other, the two columns are slightly separated when the contents are large enough to this.

screenshot_20190121-213711_trinity

### CODE REVIEW

File: src/mobile/src/ui/components/SettingsContent.js [hunk 1]
```diff
@@ -134,7 +135,7 @@ export const renderSettingsRows = (rows, theme) => {
                                     <View style={styles.content}>
                                         <Text style={[styles.titleText, textColor]}>{row.name}</Text>
                                         {row.currentSetting && (
-                                            <Text numberOfLines={1} style={[styles.settingText, textColor]}>
+                                            <Text numberOfLines={1} style={[styles.settingText, textColor, marginLeft]}>
```
Comment (rajivshah3) [inline src/mobile/src/ui/components/SettingsContent.js]: The `marginLeft` can just be included here: https://github.com/iotaledger/trinity-wallet/pull/972/files#diff-2e87c3da0f3ff562affa311e504e0161R102

```
settingText: {
        fontFamily: 'SourceSansPro-Light',
        fontSize: Styling.fontSize3,
        backgroundColor: 'transparent',
        marginLeft: 5,
    },
```

Comment (rajivshah3) [reply src/mobile/src/ui/components/SettingsContent.js]: If you want to completely fix the issue, I found that this helps:

```
settingText: {
        fontFamily: 'SourceSansPro-Light',
        fontSize: Styling.fontSize3,
        backgroundColor: 'transparent',
        marginLeft: 5,
        flex: 1,
        textAlign: right,
   },
```
So it will look like this:
image

**Review by rajivshah3 — APPROVED** [review]
Thanks @delki8 ! Looks great
